#service
server:
  port: 8089
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sell_new?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#数据null不返回前端
  #jackson:
    #default-property-inclusion: non_null


enableSwagger: true

wechat:
  appId: wx4dfdb027e86432e3
  appSecret: fd572358868d16dca274bdfc3b304b02
  openAppId:
  openAppSecret:


projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc
logging:
  level:
    com.web.sell.mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml


