#spring 基础配置
spring:
    profiles:
        active: dev


#分页配置
pagehelper:
    dialect: com.github.pagehelper.PageHelper
    support-methods-arguments: true
    params: count=countSql
    reasonable: true

